import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";

// import required modules
import { Navigation } from "swiper/modules";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <main>
          <div className="itit_top">
            <div className="itit_top_group">
              <div className="itit_top_text">
                <p className="itit_top_text_p">ご予約はお電話でお受けします</p>
                <a className="itit_top_text_phone" href="tel:0178-25-8425">
                  0178-25-8425
                </a>
              </div>
              <div className="itit_top_phone-link-group">
                <a className="itit_top_phone-link" href="tel:0178-25-8425">
                  電話する
                </a>
              </div>
              <div className="itit_top_image-gruop">
                <img
                  className="itit_top_image-pc"
                  src="/it-feels-it-top-image.png"
                  alt="top-image pc画像"
                />
                <img
                  className="itit_top_image-sp"
                  src="/topimage_sp.png"
                  alt="top-image sp画像"
                />
              </div>
            </div>
          </div>

          <section id="menu">
            <div className="itit_menu2">
              <div className="itit_menu2_group">
                <h1 className="itit_menu2_title">脱毛メニュー</h1>
                <p className="itit_menu2_text">(税込)</p>
              </div>
              <div className="itit_menu2_button">
                <button className="itit_menu2_button-woman">女性</button>
                <button className="itit_menu2_button-man">男性</button>
              </div>
            </div>

            <div className="itit_menu2_card">
              <div className="itit_menu2_card-grid">
                <img
                  src="/datumou-bui.svg"
                  alt="おでこ"
                  className="itit_menu2_card-image"
                />
                <div className="itit_menu2_card-info">
                  <span className="itit_menu2_card-info_label">おでこ</span>
                  <span className="itit_menu2_card-info_price">¥2,500</span>
                </div>
              </div>
              <div className="itit_menu2_card-grid">
                <img
                  src="/datumou-bui.svg"
                  alt="おでこ"
                  className="itit_menu2_card-image"
                />
                <div className="itit_menu2_card-info">
                  <span className="itit_menu2_card-info_label">おでこ</span>
                  <span className="itit_menu2_card-info_price">¥2,500</span>
                </div>
              </div>
              <div className="itit_menu2_card-grid">
                <img
                  src="/datumou-bui.svg"
                  alt="おでこ"
                  className="itit_menu2_card-image"
                />
                <div className="itit_menu2_card-info">
                  <span className="itit_menu2_card-info_label">おでこ</span>
                  <span className="itit_menu2_card-info_price">¥2,500</span>
                </div>
              </div>
              <div className="itit_menu2_card-grid">
                <img
                  src="/datumou-bui.svg"
                  alt="おでこ"
                  className="itit_menu2_card-image"
                />
                <div className="itit_menu2_card-info">
                  <span className="itit_menu2_card-info_label">おでこ</span>
                  <span className="itit_menu2_card-info_price">¥2,500</span>
                </div>
              </div>
            </div>
          </section>

          <section className="itit_payment_method">
            <div className="itit_payment_method_group">
              <h1 className="itit_payment_method_title">お支払い方法</h1>
            </div>
            <div className="itit_payment_method_list">
              <div className="itit_payment_method_item">
                <img
                  className="itit_payment_method_image"
                  src="/Cash.svg"
                  alt="現金"
                />
                <div className="itit_payment_method_item_group">
                  <span className="itit_payment_method_badge">1</span>
                  <p className="itit_payment_method_text">現金</p>
                </div>
              </div>
              <div className="itit_payment_method_item">
                <img
                  className="itit_payment_method_image"
                  src="/CreditCard.svg"
                  alt="クレジットカード"
                />
                <div className="itit_payment_method_item_group">
                  <span className="itit_payment_method_badge">2</span>
                  <p className="itit_payment_method_text">クレジットカード</p>
                </div>
              </div>
              <div className="itit_payment_method_item">
                <img
                  className="itit_payment_method_image"
                  src="/IC-QR.svg"
                  alt="QR・電子マネー"
                />
                <div className="itit_payment_method_item_group">
                  <span className="itit_payment_method_badge">3</span>
                  <p className="itit_payment_method_text">QR, 電子マネー</p>
                </div>
              </div>
            </div>
          </section>

          <section>
            <div className="itit_reservation">
              <div className="itit_reservation_group">
                <h1 className="itit_reservation_title">ご予約</h1>
                <p className="itit_reservation_text">
                  当店は完全予約制です
                  <br /> ご予約は電話にて承っています <br />
                  AM 09:00〜PM 18:00(月曜定休)
                </p>
                <a className="itit_reservation_tel" href="tel:0178-25-8425">
                  tel: 0178-25-8425
                </a>
                <div className="itit_reservation_tel-link-group">
                  <a
                    className="itit_reservation_tel-link"
                    href="tel:0178-25-8425"
                  >
                    0178-25-8425
                  </a>
                </div>
              </div>
            </div>
          </section>

          <section id="staff" className="itit_staff">
            <h2 className="itit_staff_title">スタッフ</h2>
            <div className="itit_staff_list">
              <Swiper
                navigation={{
                  nextEl: "#staff-button-next",
                  prevEl: "#staff-button-prev",
                }}
                modules={[Navigation]}
                className="mySwiper"
                breakpoints={{
                  768: {
                    slidesPerView: 3,
                    spaceBetween: 10,
                  },
                }}
              >
                <SwiperSlide>
                  <div className="itit_staff_item">
                    <div className="itit_staff_image"></div>
                    <p className="itit_staff_role">ヘアスタイリスト</p>
                    <h3 className="itit_staff_name">ヤマミチ アツシ</h3>
                    <p className="itit_staff_message">
                      いつも楽しくをモットーに！
                    </p>
                  </div>
                </SwiperSlide>
                <SwiperSlide>
                  <div className="itit_staff_item">
                    <div className="itit_staff_image"></div>
                    <p className="itit_staff_role">ヘアスタイリスト</p>
                    <h3 className="itit_staff_name">ヤマミチ アツシ</h3>
                    <p className="itit_staff_message">
                      いつも楽しくをモットーに！
                    </p>
                  </div>
                </SwiperSlide>
                <SwiperSlide>
                  <div className="itit_staff_item">
                    <div className="itit_staff_image"></div>
                    <p className="itit_staff_role">ヘアスタイリスト</p>
                    <h3 className="itit_staff_name">ヤマミチ アツシ</h3>
                    <p className="itit_staff_message">
                      いつも楽しくをモットーに！
                    </p>
                  </div>
                </SwiperSlide>
              </Swiper>
            </div>
            <div className="itit_staff_arrow-group">
              <button
                id="staff-button-prev"
                className=" itit_staff_arrow-group_button"
                tabIndex={0}
                role="button"
              >
                <img src="/chevron_left.svg" alt="左矢印" />
              </button>
              <button
                id="staff-button-next"
                className="itit_staff_arrow-group_button"
                tabIndex={0}
                role="button"
              >
                <img src="/chevron_right.svg" alt="右矢印" />
              </button>
            </div>
          </section>

          <section id="information">
            <div className="itit_information">
              <div className="itit_information_group">
                <h2 className="itit_information_title">新着情報</h2>
                <p className="itit_information_subtitle">(Instagram)</p>
                <div className="itit_information_instagram_group">
                  <Swiper
                    navigation={{
                      nextEl: "#information-button-next",
                      prevEl: "#information-button-prev",
                    }}
                    modules={[Navigation]}
                    className="mySwiper"
                    breakpoints={{
                      768: {
                        slidesPerView: 3,
                        spaceBetween: 10,
                      },
                    }}
                  >
                    <SwiperSlide>
                      <div className="itit_information_instagram">
                        <div className="itit_information_instagram_item">
                          <img
                            className="itit_information_instagram_logo"
                            src="/Instagram_logo.svg"
                            alt="Instagram画像"
                          />
                          <p className="itit_information_instagram_name">
                            itfeelsit
                          </p>
                          <p className="itit_information_instagram_date">
                            2024/01/01
                          </p>
                        </div>
                        <img
                          className="itit_information_instagram_image"
                          src="/staff.png"
                          alt="スタッフ画像"
                        />
                        <p className="itit_information_instagram_text">
                          今年も皆様のおかげで無事に1年終えることができました🥲
                          ....
                        </p>
                        <a
                          className="itit_information_instagram_more"
                          href="https://www.instagram.com/itfeelsit/"
                          target="_blank"
                        >
                          もっと読む→
                        </a>
                      </div>
                    </SwiperSlide>
                    <SwiperSlide>
                      <div className="itit_information_instagram">
                        <div className="itit_information_instagram_item">
                          <img
                            className="itit_information_instagram_logo"
                            src="/Instagram_logo.svg"
                            alt="Instagram画像"
                          />
                          <p className="itit_information_instagram_name">
                            itfeelsit
                          </p>
                          <p className="itit_information_instagram_date">
                            2024/01/01
                          </p>
                        </div>
                        <img
                          className="itit_information_instagram_image"
                          src="/staff.png"
                          alt="スタッフ画像"
                        />
                        <p className="itit_information_instagram_text">
                          今年も皆様のおかげで無事に1年終えることができました🥲
                          ....
                        </p>
                        <a
                          className="itit_information_instagram_more"
                          href="https://www.instagram.com/itfeelsit/"
                          target="_blank"
                        >
                          もっと読む→
                        </a>
                      </div>
                    </SwiperSlide>
                    <SwiperSlide>
                      <div className="itit_information_instagram">
                        <div className="itit_information_instagram_item">
                          <img
                            className="itit_information_instagram_logo"
                            src="/Instagram_logo.svg"
                            alt="Instagram画像"
                          />
                          <p className="itit_information_instagram_name">
                            itfeelsit
                          </p>
                          <p className="itit_information_instagram_date">
                            2024/01/01
                          </p>
                        </div>
                        <img
                          className="itit_information_instagram_image"
                          src="/staff.png"
                          alt="スタッフ画像"
                        />
                        <p className="itit_information_instagram_text">
                          今年も皆様のおかげで無事に1年終えることができました🥲
                          ....
                        </p>
                        <a
                          className="itit_information_instagram_more"
                          href="https://www.instagram.com/itfeelsit/"
                          target="_blank"
                        >
                          もっと読む→
                        </a>
                      </div>
                    </SwiperSlide>
                  </Swiper>
                </div>
              </div>
            </div>
            <div className="itit_information_arrow-group">
              <button
                id="information-button-prev"
                className=" itit_information_arrow-group_button"
                tabIndex={0}
                role="button"
              >
                <img src="/chevron_left.svg" alt="左矢印" />
              </button>
              <button
                id="information-button-next"
                className="itit_information_arrow-group_button"
                tabIndex={0}
                role="button"
              >
                <img src="/chevron_right.svg" alt="右矢印" />
              </button>
            </div>
          </section>

          <section id="access">
            <div className="itit_access">
              <div className="itit_access_group">
                <h2 className="itit_access_title">アクセス</h2>
              </div>
            </div>
          </section>

          <section>
            <div className="itit_ReFa">
              <div className="itit_ReFa_group">
                <div className="itit_ReFa_image-group">
                  <img
                    className="itit_ReFa_image"
                    src="/ReFa.png"
                    alt="ReFaの画像"
                  />
                </div>
                <div className="itit_ReFa_text-group">
                  <h2 className="itit_ReFa_title">ReFa 商品をご購入できます</h2>
                  <ul className="itit_ReFa_text-list">
                    <li className="itit_ReFa_text">
                      <img
                        src="/check.svg"
                        alt="チェックマーク"
                        className="itit_ReFa_text_list_check"
                      />
                      メーカー直営オンラインショップ(B happy)での買い物が可能！
                    </li>
                    <li className="itit_ReFa_text">
                      <img
                        src="/check.svg"
                        alt="チェックマーク"
                        className="itit_ReFa_text_list_check"
                      />
                      B happy会員限定クーポンプレゼント
                    </li>
                    <li className="itit_ReFa_text">
                      <img
                        src="/check.svg"
                        alt="チェックマーク"
                        className="itit_ReFa_text_list_check"
                      />
                      お買い物ポイント付与
                    </li>
                  </ul>
                  <p className="itit_ReFa_text_sp">
                    当店では、ReFaなどMTG製品をご購入できます。
                  </p>
                </div>
              </div>
            </div>
          </section>
        </main>
        <Footer />
      </div>
    </>
  );
}
