import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <main>
          <div className="itit_top">
            <div className="itit_top_group">
              <div className="itit_top_text">
                <p className="itit_top_text_p">ご予約はお電話でお受けします</p>
                <p className="itit_top_text_phone">0178-96-2581</p>
              </div>
              <img
                className="itit_top_image"
                src="/it-feels-it-top-image.png"
                alt="top-image画像"
              />
            </div>
          </div>

          <section>
            <div className="itit_menu">
              <div className="itit_menu_group">
                <h1 className="itit_menu_title">メニューと料金</h1>
              </div>
              <div className="itit_menu_price-table_group">
                <div className="itit_menu_price-table">
                  <p className="itit_menu_price-table_title">ヘア</p>
                  <ul className="itit_menu_price-table_list">
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        カット
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥4,000
                      </span>
                    </li>
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        カット・カラー
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥8,000〜
                      </span>
                    </li>
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        カット・パーマ
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥8,000〜
                      </span>
                    </li>
                  </ul>
                </div>

                <div className="itit_menu_price-table">
                  <p className="itit_menu_price-table_title">ストレート</p>
                  <ul className="itit_menu_price-table_list">
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        縮毛矯正
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥4,000
                      </span>
                    </li>
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        酸性ストレートパーマ
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥8,000〜
                      </span>
                    </li>
                  </ul>
                </div>
              </div>

              <div className="itit_menu_price-table_group">
                <div className="itit_menu_price-table">
                  <p className="itit_menu_price-table_title">ハイライト</p>
                  <ul className="itit_menu_price-table_list">
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        ハイライトS
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥4,000
                      </span>
                    </li>
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        ハイライトM
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥8,000〜
                      </span>
                    </li>
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        ハイライトL
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥8,000〜
                      </span>
                    </li>
                  </ul>
                </div>

                <div className="itit_menu_price-table">
                  <p className="itit_menu_price-table_title">トリートメント</p>
                  <ul className="itit_menu_price-table_list">
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        トリートメント
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥4,000
                      </span>
                    </li>
                  </ul>
                </div>
              </div>

              <div className="itit_menu_price-table_group">
                <div className="itit_menu_price-table">
                  <p className="itit_menu_price-table_title">出張</p>
                  <ul className="itit_menu_price-table_list">
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        カット
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥2,000
                      </span>
                    </li>
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        カット＋顔剃り
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥2,500
                      </span>
                    </li>
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        顔剃り
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥1,000
                      </span>
                    </li>
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        カット＋顔剃り＋カラー
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥5,000
                      </span>
                    </li>
                  </ul>
                </div>

                <div className="itit_menu_price-table">
                  <p className="itit_menu_price-table_title">自宅出張</p>
                  <ul className="itit_menu_price-table_list">
                    <li className="itit_menu_price-table_list_item">
                      <span className="itit_menu_price-table_list_item_name">
                        自宅出張
                      </span>
                      <span className="itit_menu_price-table_list_item_price">
                        ¥5,000
                      </span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </section>

          <section className="itit_payment_method">
            <div className="itit_payment_method_group">
              <h1 className="itit_payment_method_title">お支払い方法</h1>
            </div>
            <div className="itit_payment_method_list">
              <div className="itit_payment_method_item">
                <img
                  className="itit_payment_method_image"
                  src="/cash.png"
                  alt="現金"
                />
                <span className="itit_payment_method_badge">1</span>
                <p className="itit_payment_method_text">現金</p>
              </div>
              <div className="itit_payment_method_item">
                <img
                  className="itit_payment_method_image"
                  src="/creditcard.png"
                  alt="クレジットカード"
                />
                <span className="itit_payment_method_badge">2</span>
                <p className="itit_payment_method_text">クレジットカード</p>
              </div>
              <div className="itit_payment_method_item">
                <img
                  className="itit_payment_method_image"
                  src="/qric.png"
                  alt="QR・電子マネー"
                />
                <span className="itit_payment_method_badge">3</span>
                <p className="itit_payment_method_text">QR, 電子マネー</p>
              </div>
            </div>
          </section>

          <section>
            <div className="itit_reservation">
              <div className="itit_reservation_group">
                <h1 className="itit_reservation_title">ご予約</h1>
                <p className="itit_reservation_text">
                  当店は完全予約制です
                  <br /> ご予約は電話にて承っています <br />
                  AM 09:00〜PM 18:00(月曜定休)
                </p>
                <p className="itit_reservation_tel">tel: 0178-96-2581</p>
              </div>
            </div>
          </section>

          <section className="staff">
            <h2 className="staff_title">スタッフ</h2>
            <div className="staff_list">
              <div className="staff_item">
                <div className="staff_image"></div>
                <p className="staff_role">ヘアスタイリスト</p>
                <h3 className="staff_name">ヤマミチ アツシ</h3>
                <p className="staff_message">いつも楽しくをモットーに！</p>
              </div>
              <div className="staff_item">
                <div className="staff_image"></div>
                <p className="staff_role">ヘアスタイリスト</p>
                <h3 className="staff_name">ヤマミチ アツシ</h3>
                <p className="staff_message">いつも楽しくをモットーに！</p>
              </div>
              <div className="staff_item">
                <div className="staff_image"></div>
                <p className="staff_role">ヘアスタイリスト</p>
                <h3 className="staff_name">ヤマミチ アツシ</h3>
                <p className="staff_message">いつも楽しくをモットーに！</p>
              </div>
            </div>
          </section>
        </main>
      </div>
    </>
  );
}
