import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <main>
          <div className="itit_top">
            <div className="itit_top_group">
              <div className="itit_top_text">
                <p className="itit_top_text_p">ご予約はお電話でお受けします</p>
                <p className="itit_top_text_phone">0178-96-2581</p>
              </div>
              <img
                className="itit_top_image"
                src="/it-feels-it-top-image.png"
                alt="top-image画像"
              />
            </div>
          </div>

          <section>
            <div className="itit_menu">
              <div className="itit_menu_group">
                <h1 className="itit_menu_title">メニューと料金</h1>
              </div>

              <div className="itit_menu_price-table_title-gruop">
                <p className="itit_menu_price-table_title">ヘア</p>
                <p className="itit_menu_price-table_title_2">ストレート</p>
              </div>
              <div className="itit_menu_price-table">
                <table className="itit_menu_price-category">
                  <tbody>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name">カット</td>
                      <td className="itit_menu_price">¥4,000</td>
                    </tr>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name">カット・カラー</td>
                      <td className="itit_menu_price">¥8,000〜</td>
                    </tr>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name">カット・パーマ</td>
                      <td className="itit_menu_price">¥8,000〜</td>
                    </tr>
                  </tbody>
                </table>

                <table className="itit_menu_price-category_2">
                  <tbody>
                    <tr className="itit_menu_category-title"></tr>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name">縮毛矯正</td>
                      <td className="itit_menu_price">¥4,000</td>
                    </tr>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name">酸性ストレートパーマ</td>
                      <td className="itit_menu_price">¥8,000〜</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <div>
                <p className="itit_menu_price-table_title_3">ハイライト</p>
              </div>
              <div className="itit_menu_price-table">
                <table className="itit_menu_price-category">
                  <tbody>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name">ハイライトS</td>
                      <td className="itit_menu_price">¥4,000</td>
                    </tr>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name">ハイライトM</td>
                      <td className="itit_menu_price">¥8,000〜</td>
                    </tr>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name">ハイライトL</td>
                      <td className="itit_menu_price">¥8,000〜</td>
                    </tr>
                  </tbody>
                </table>

                <table className="itit_menu_price-category_3">
                  <tbody>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name_1">トリートメント</td>
                      <td className="itit_menu_price">¥4,000〜</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <div>
                <p className="itit_menu_price-table_title_3">出張</p>
              </div>
              <div className="itit_menu_price-table">
                <table className="itit_menu_price-category">
                  <tbody>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name">カット</td>
                      <td className="itit_menu_price">¥2,000</td>
                    </tr>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name">カット＋顔剃り</td>
                      <td className="itit_menu_price">¥2500</td>
                    </tr>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name">顔剃り</td>
                      <td className="itit_menu_price">¥1000</td>
                    </tr>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name">カット＋顔剃り＋カラー</td>
                      <td className="itit_menu_price">¥5,000</td>
                    </tr>
                  </tbody>
                </table>

                <table className="itit_menu_price-category_3">
                  <tbody>
                    <tr className="itit_menu_table">
                      <td className="itit_menu_name_1">自宅出張</td>
                      <td className="itit_menu_price">¥5,000</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </section>
        </main>
      </div>
    </>
  );
}
