import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <main>
          <div className="itit_main">
            <div className="itit_main_group">
              <div className="itit_main_group_text">
                <p>ご予約はお電話でお受けします</p>
                <p>0178-96-2581</p>
              </div>
              <img
                className="itit_main_image"
                src="/it-feels-it-top-image.png"
                alt="top-image画像"
              />
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
